---
title: "Analysis of IGN dataset in R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/finn/medium_articles/ign_in_r")
getwd()
```

```{r}
# install tidyverse and readr for data manipulation
install.packages("tidyverse", dependencies=TRUE, repos="http://cran.wustl.edu/")
```


```{r}
# install.packages("readr", dependencies=TRUE)
```

```{r}
# install.packages("here", dependencies = TRUE)
```


```{r}
# load packages
library(tidyverse)
library(readr)
```

```{r}
# read csv of ign data into a dataframe
ign <- read.csv(here::here('ign.csv'), stringsAsFactors = FALSE)
head(ign)
```

```{r}
# a summary of the variables in the dataframe
str(ign)
summary(ign)
```

```{r}
names(ign)
```

Top-rated titles
```{r}
ign[order(ign$score, decreasing = TRUE),]
```

Top-rated genre
```{r}
ign %>%
  group_by(genre) %>%
  summarise(mean_score = mean(score)) %>%
  arrange(desc(mean_score)) %>%
  head(., n=10) %>%
  ggplot() +
  geom_bar(aes(x=reorder(genre, -mean_score), y=mean_score, fill=genre), stat="identity") +
  guides(fill = FALSE) +
  labs(title = "Top 10 Genres by Mean Review Score", x="Genre", y="Mean Review Score") +
  theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1))
```

Top-rated platforms
```{r}
ign %>%
  group_by(platform) %>%
  summarise(mean_score = mean(score)) %>%
  arrange(desc(mean_score)) %>%
  head(., n=10) %>%
  ggplot() +
  geom_bar(aes(x=reorder(platform, -mean_score), y=mean_score, fill = platform), stat="identity") +
  geom_label(aes(x=reorder(platform, -mean_score), y=mean_score, label=round(mean_score, digits = 2))) +
  labs(title = "Top 10 Platforms by Mean Review Score", x="Platform", y="Mean Review Score") +
  theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1)) + 
  guides(fill = FALSE)
```

Number of Games in Each Platform
```{r}
ign %>%
  group_by(platform) %>%
  summarise(counts = n()) %>%
  arrange(desc(counts)) %>%
  head(., n=10) %>%
  ggplot() +
  geom_bar(aes(x=reorder(platform, -counts), y=counts, fill=platform), stat="identity") +
  geom_label(aes(x=reorder(platform, -counts), y=counts, label = counts)) + 
  labs(title = "Top 10 Platforms by Number of Games", x="Platform", y="Total Number of Games") +
  theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1)) + 
  guides(fill = FALSE)
```

String split function
```{r}
# string split function to get the main game genre
get_genre <- function(string) {
  length <- sapply(strsplit(string, ","), length)
  return(sapply(strsplit(string,","), function(x) x[1]))
}
get_genre("Compilation, Compilation")
```

```{r}
# creating new column for main genre based on above created function
ign$main_genre <- get_genre(ign$genre)
unique(ign$main_genre)
```

```{r}
# games that dont have a genre
ign[is.na(ign$main_genre),]
```

```{r}
# checking to see if NA are dropped
ign <- ign[!is.na(ign$main_genre),]
dim(ign)
```

```{r}
# checking for any other missing values
apply(ign, 2, function(x) any(is.na(x)))
```

```{r}
ign %>%
  group_by(main_genre) %>%
  summarise(mean_score = mean(score)) %>%
  arrange(desc(mean_score)) %>%
  head(., n=10) %>%
  ggplot() +
  geom_bar(aes(x=reorder(main_genre, -mean_score), y=mean_score, fill = main_genre), stat="identity") +
  labs(title = "Top 10 Main Genres by Mean Review Score", x="Main Genre", y="Mean Review Score") +
  theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1)) + 
  guides(fill = FALSE)
```

```{r}
ign %>%
  group_by(main_genre) %>%
  summarise(mean_score = mean(score)) %>%
  arrange(desc(mean_score)) %>%
  ggplot() +
  geom_bar(aes(x=reorder(main_genre, -mean_score), y=mean_score, fill = main_genre), stat="identity") +
  labs(title = "All Main Genres by Mean Review Score", x="Main Genre", y="Mean Review Score") +
  theme(axis.text.x = element_text(size = 10, angle = 60, hjust = 1)) + 
  guides(fill = FALSE)
```

```{r}
ign[ign$main_genre == 'Hardware',]
```

```{r}
ign %>%
  group_by(main_genre) %>%
  summarise(mean_score = n()) %>%
  arrange(desc(mean_score)) %>%
  ggplot() +
  geom_bar(aes(x=reorder(main_genre, -mean_score), y=mean_score, fill = main_genre), stat="identity") +
  labs(title = "All Main Genres by Mean Review Score", x="Main Genre", y="Mean Review Score") +
  theme(axis.text.x = element_text(size = 10, angle = 60, hjust = 1)) + 
  guides(fill = FALSE)
```

Group by Title

